FROM ubuntu:16.04

MAINTAINER Alex Harvey

RUN apt-get update && apt-get install -y wget

# Get buildroot
RUN mkdir /buildroot
WORKDIR /buildroot/
RUN wget https://buildroot.org/downloads/buildroot-2017.11.1.tar.gz
RUN tar xvzf buildroot-2017.11.1.tar.gz

# Get build requirements
RUN apt-get install -y patch cpio python unzip rsync bc bzip2 ncurses-dev git make g++ python-matplotlib python-numpy

# Download all the required files
COPY vm/buildroot.config /buildroot/buildroot-2017.11.1/.config
COPY vm/linux.config /buildroot/buildroot-2017.11.1/linux.config
WORKDIR /buildroot/buildroot-2017.11.1/
RUN make source

# CMD /buildroot/buildroot-2017.11.1/make
