CPE_ID_PKG5_VERSION = 57

CPE_ID_PKG5_CPE_ID_VENDOR = foo
CPE_ID_PKG5_CPE_ID_PRODUCT = bar
CPE_ID_PKG5_CPE_ID_VERSION = 42
CPE_ID_PKG5_CPE_ID_UPDATE = b2
CPE_ID_PKG5_CPE_ID_PREFIX = cpe:2.4:a

HOST_CPE_ID_PKG5_CPE_ID_VENDOR = baz
HOST_CPE_ID_PKG5_CPE_ID_PRODUCT = fuz
HOST_CPE_ID_PKG5_CPE_ID_VERSION = 43
HOST_CPE_ID_PKG5_CPE_ID_UPDATE = b3
HOST_CPE_ID_PKG5_CPE_ID_PREFIX = cpe:2.5:a

$(eval $(generic-package))
$(eval $(host-generic-package))
