#!/bin/sh

#
# Minimal pg_config implementation as replacement for the native pg_config application
#

prefix=/usr

case "$1" in
  --includedir)
	echo "$prefix/include"
	;;
  --pkgincludedir)
	echo "$prefix/include/postgresql"
	;;
  --includedir-server)
	echo "$prefix/include/postgresql/server"
	;;
  --libdir)
	echo "$prefix/lib"
	;;
  --version)
	echo "PostgreSQL @POSTGRESQL_VERSION@"
	;;
  --configure)
	echo "@POSTGRESQL_CONF_OPTIONS@"
	;;
  --pgxs)
	echo "$prefix/lib/postgresql/pgxs/src/makefiles/pgxs.mk"
	;;
  --cflags)
	echo "@TARGET_CFLAGS@"
	;;
  --cc)
	echo "@TARGET_CC@"
	;;
  --pkglibdir)
	echo "/usr/lib/postgresql"
	;;
  --bindir)
	echo "/usr/bin"
	;;
  --sharedir)
	echo "/usr/share/postgresql"
	;;
  --localedir)
	echo "/usr/share/locale"
	;;
  --docdir)
	echo "/usr/share/doc/postgresql"
	;;
  --mandir)
	echo "/usr/share/man"
	;;
  *)
	echo "Usage: $0 {OPTION}"
	echo
	echo "Options:"
	echo
	echo "	--includedir		show location of C header files of the client interfaces"
	echo "	--pkgincludedir		show location of other C header files"
	echo "	--includedir-server	show location of C header files for the server"
	echo "	--libdir		show location of object code libraries"
	echo "	--version		show the PostgreSQL version"
	echo "	--configure		show options given to configure script"
	echo "	--pgxs			show location of extension makefile"
	echo "	--cflags		show CFLAGS value used when PostgreSQL was built"
	echo "	--cc			show CC value used when PostgreSQL was built"
	echo "	--pkglibdir		show location of dynamically loadable modules"
	echo "	--bindir		show location of user executables"
	echo "	--sharedir		show location of architecture-independent support files"
	echo "	--localedir		show location of locale support files"
	echo "	--docdir		show location of documentation files"
	echo "	--mandir		show location of manual pages"
esac
