#!/bin/bash

SRC=$( cd -P -- "$(dirname -- "$(command -v -- "$0")")" && pwd -P )

if grep -Eq "^GXL.+S905W" /sys/devices/soc0/soc_id; then
  echo "Amlogic S905W detected."
  bash "$SRC/init_j80"
elif grep -Eq "^AXG" /sys/devices/soc0/soc_id; then
  echo "Amlogic AXG detected."
  bash "$SRC/init_j100"
else
  echo "SoC detection failed. Unable to init"
fi

