#!/bin/bash

swap_size=512 # MiBs
swap_part=/mnt/data
swap_path=/mnt/data/swapfile
swap_priority=-3

swap_free_space=$(env stat -f -c '%a*%S/1024/1024' $swap_part | bc)

make_swap()
{
  if [ $swap_free_space -ge $swap_size ]; then
    echo "allocating file for swap ..."
    if fallocate -l ${swap_size}M $swap_path; then
      chmod 0600 $swap_path
      if mkswap "$swap_path"; then
        if swapon --verbose --priority $swap_priority "$swap_path"; then
          echo "swap added succesfully"
        else
          echo "swapon $swap_path failed"
        fi
      else
        echo "mkswap $swap_path failed"
      fi
    else
      echo "allocate file $swap_path with $swap_size MB size failed."
    fi
  fi
}


make_swap_axg() {
  if [ -f "$swap_path" ]; then
    echo "Swap file exist. Check and enable swap."
    make_swap
  elif grep -Eq "^GXL.+S905W" /sys/devices/soc0/soc_id; then
    echo "Amlogic S905W detected. Skip swap file creation"
  elif grep -Eq "^AXG" /sys/devices/soc0/soc_id; then
    echo "Amlogic AXG detected. Skip swap file creation"
  else
    echo "SoC detection failed. Unable to create swap file"
  fi
}

make_swap_axg
