#!/bin/bash

GPIO_DIRECTION_OUTPUT=0
#GPIO_DIRECTION_INPUT=1

GPIO_ACTIVE_LOW=0
GPIO_ACTIVE_HIGH=1

configure_gpio() {
  echo "${0}: Configure: gpio=${1}, direction=${2}, active_level=${3}"

  if [ ! -d "/sys/class/gpio/gpio${1}" ]; then
    echo "${1}" > /sys/class/gpio/export
    if [ ! -d "/sys/class/gpio/gpio${1}" ]; then
      echo "${0}: *** Error: Failed to configure GPIO ${1}"
      exit 1
    fi
  fi

  if [ "${2}" == "${GPIO_DIRECTION_OUTPUT}" ]; then
    echo "out" > "/sys/class/gpio/gpio${1}/direction"
  else
    echo "in" > "/sys/class/gpio/gpio${1}/direction"
  fi

  if [ "${3}" == "${GPIO_ACTIVE_LOW}" ]; then
    echo 1 > "/sys/class/gpio/gpio${1}/active_low"
  fi 
}

echo "${0}: Configure GPIOs ..."

# Zigbee module: RESET, BOOT
configure_gpio "507" "${GPIO_DIRECTION_OUTPUT}" "${GPIO_ACTIVE_HIGH}"
configure_gpio "510" "${GPIO_DIRECTION_OUTPUT}" "${GPIO_ACTIVE_HIGH}"
# Z-Wave module: RESET, SUSPEND
configure_gpio "490" "${GPIO_DIRECTION_OUTPUT}" "${GPIO_ACTIVE_HIGH}"
configure_gpio "491" "${GPIO_DIRECTION_OUTPUT}" "${GPIO_ACTIVE_HIGH}"
# LED
configure_gpio "474" "${GPIO_DIRECTION_OUTPUT}" "${GPIO_ACTIVE_HIGH}"


echo "${0}: Turn off LED ..."
echo 0 > /sys/class/gpio/gpio474/value

echo "${0}: Reset Zigbee module ..."
echo 1 > /sys/class/gpio/gpio510/value
echo 1 > /sys/class/gpio/gpio507/value
sleep 1
echo 0 > /sys/class/gpio/gpio507/value

echo "${0}: Reset Z-Wave module ..."
# Optional SUSPEND pin
#echo 1 > /sys/class/gpio/gpio491/value
echo 1 > /sys/class/gpio/gpio490/value
sleep 1
echo 0 > /sys/class/gpio/gpio490/value

exit 0
