#!/bin/sh
set -e

# Load configs
. /mnt/data/supervisor.config

HASSIO_DATA=/mnt/data/$DATA_FOLDER
HASSIO_IMAGE_ID=$(docker inspect --format='{{.Id}}' $SUPERVISOR)
HASSIO_CONTAINER_ID=$(docker inspect --format='{{.Image}}' hassio_supervisor || echo "")

runSupervisor() {
    docker rm --force hassio_supervisor || true
    docker run --name hassio_supervisor \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -v /var/run/dbus:/var/run/dbus \
        -v $HASSIO_DATA:/data \
        -e SUPERVISOR_SHARE=$HASSIO_DATA \
        -e SUPERVISOR_NAME=hassio_supervisor \
        -e HOMEASSISTANT_REPOSITORY=$HOMEASSISTANT \
        $SUPERVISOR
}

mkdir -p $HASSIO_DATA
([ "$HASSIO_IMAGE_ID" = "$HASSIO_CONTAINER_ID" ] && docker start --attach hassio_supervisor) || runSupervisor
