#!/bin/sh
set -e

# Load configs
CONFIG_FILE=/mnt/data/hassio.json

PROFILES_DIR="$(jq --raw-output '.apparmor_profiles // empty' ${CONFIG_FILE})"
CACHE_DIR=${PROFILES_DIR/cache}
REMOVE_DIR=${PROFILES_DIR/remove}

# Check folder structure
mkdir -p PROFILES_DIR
mkdir -p CACHE_DIR
mkdir -p REMOVE_DIR
