#!/bin/sh
set -e

# Check if hassio-config is present
if ! findfs LABEL="hassio-config" > /dev/null; then
    echo "[Warning] No hassio-config partition found!"
    exit 0
fi

# Mount config partition
mount -o ro LABEL="hassio-config" /mnt/config

##
# NetworkManager
if ls /mnt/config/network-* > /dev/null; then
    echo "[Info] Update NetworkManager connections!"

    rm -rf /etc/NetworkManager/system-connections/*
    cp -f /mnt/config/network-* /etc/NetworkManager/system-connections/
fi

##
# SSH know hosts
if [ -f /mnt/config/known_hosts ]; then
    echo "[Info] Update SSH known_hosts!"

    cp -f /mnt/config/known_hosts /root/.ssh/known_hosts
    chmod 600 /root/.ssh/known_hosts
fi

##
# Firmware update


# Cleanup config partition
umount /mnt/config
