#!/bin/sh
set -e

DEVICE_CHILD=$(findfs LABEL="hassos-data")
DEVICE_ROOT="/dev/$(lsblk -no pkname ${DEVICE_CHILD})"

# Need resize
if [ $(sgdisk -E ${DEVICE_ROOT}) -le 2048 ]; then
    echo "[INFO] No resize of data partition needed"
    exit
fi

# Resize & Reload partition
echo "[INFO] Update hassos-data partition"
sgdisk -e ${DEVICE_ROOT}
sgdisk -d 8 -n 8:0:0 -c 8:"hassos-data" -t 8:"0FC63DAF-8483-4772-8E79-3D69D8477DE4" -u 8:"a52a4597-fa3a-4851-aefd-2fbe9f849079" ${DEVICE_ROOT}
sgdisk -v ${DEVICE_ROOT}
partx -u ${DEVICE_ROOT}

# Resize filesystem
echo "[INFO] Resize hassos-data filesystem"
e2fsck -y ${DEVICE_CHILD}
resize2fs -f ${DEVICE_CHILD}

echo "[INFO] Finish hassos-data resizing"
