#!/bin/sh
# ==============================================================================
# Run logging cli
# ==============================================================================

# Setup terminal size on serial console
if [ "${TERM}" = "vt220" ] || [ "${TERM}" = "vt102" ] || \
   [ "${TERM}" = "vt100" ]; then
	resize
fi

# Run CLI container
if [ "$(docker ps -q -f name=hassio_cli)" ]; then
    docker container exec \
        -ti hassio_cli \
        /usr/bin/cli.sh \

    # Jump to root login shell
    if [ $? -eq 10 ]; then
        /bin/ash -l
    fi
else
    echo "[WARN] Home Assistant CLI is not running! Jump into emergency console..."
    /bin/ash -l
fi

exit
