################################################################################
#
# libminiupnpc
#
################################################################################

LIBMINIUPNPC_VERSION_MAJOR = 2.1
LIBMINIUPNPC_VERSION_MINOR = 20201016
LIBMINIUPNPC_VERSION = $(LIBMINIUPNPC_VERSION_MAJOR).$(LIBMINIUPNPC_VERSION_MINOR)
LIBMINIUPNPC_SOURCE = miniupnpc-$(LIBMINIUPNPC_VERSION).tar.gz
LIBMINIUPNPC_SITE = http://miniupnp.free.fr/files
LIBMINIUPNPC_INSTALL_STAGING = YES
LIBMINIUPNPC_LICENSE = BSD-3-Clause
LIBMINIUPNPC_LICENSE_FILES = LICENSE
LIBMINIUPNPC_CPE_ID_VENDOR = miniupnp_project
LIBMINIUPNPC_CPE_ID_PRODUCT = miniupnpc
LIBMINIUPNPC_CPE_ID_VERSION = $(LIBMINIUPNPC_VERSION_MAJOR)
LIBMINIUPNPC_CPE_ID_UPDATE = $(LIBMINIUPNPC_VERSION_MINOR)

$(eval $(cmake-package))
