#!/bin/sh

if [ "$SERVICE_RESULT" = "exit-code" ] && [ "$EXIT_STATUS" = "1" ]; then
    echo "Docker exited with exit status 1, this might be caused by corrupted key.json."
    size=$(stat -c %s "/mnt/overlay/etc/docker/key.json")
    echo "key.json: ${size} bytes"
    if ! jq -e < "/mnt/overlay/etc/docker/key.json" > /dev/null || [ "${size}" -eq 0 ]; then
        echo "key.json appears to be corrupted, it is not parsable. Removing it."
        rm -f "/mnt/overlay/etc/docker/key.json"
    fi
fi
