#!/bin/sh

if [ "$SERVICE_RESULT" = "exit-code" ] && [ "$EXIT_STATUS" = "1" ]; then
    echo "Docker exited with exit status 1, this might be caused by corrupted key.json."
    size=$(stat -c %s "/etc/docker/key.json")
    echo "key.json: ${size} bytes"
    rm -f /etc/docker/key.json
fi
