#!/bin/sh
# shellcheck disable=SC2112
set -e


function mark_good() {
    rauc status mark-good
    exit 0
}

function mark_bad() {
    rauc status mark-bad
    systemctl reboot
}

#### Check system ####

# Docker state
if systemctl -q is-failed docker; then
    mark_bad
fi

# Docker state
if systemctl -q is-failed hassos-supervisor; then
    mark_bad
fi

mark_good
