#!/bin/sh

overlay_dir=/mnt/overlay/etc/upper

# TODO we could do migrate here if ${overlay_dir} does not exist

mkdir -p "${overlay_dir}"
mkdir -p /mnt/overlay/etc/workdir

# Network
mkdir -p "${overlay_dir}"/NetworkManager/system-connections
