#!/bin/bash

GPIO_DIRECTION_OUTPUT=0
GPIO_DIRECTION_INPUT=1

GPIO_ACTIVE_LOW=0
GPIO_ACTIVE_HIGH=1

configure_gpio() {
  echo "${0}: Configure: gpio=${1}, direction=${2}, active_level=${3}"

  if [ ! -d "/sys/class/gpio/gpio${1}" ]; then
    echo "${1}" > /sys/class/gpio/export
    if [ ! -d "/sys/class/gpio/gpio${1}" ]; then
      echo "${0}: *** Error: Failed to configure GPIO ${1}"
      exit 1
    fi
  fi

  if [ "${2}" == "${GPIO_DIRECTION_OUTPUT}" ]; then
    echo "out" > "/sys/class/gpio/gpio${1}/direction"
  else
    echo "in" > "/sys/class/gpio/gpio${1}/direction"
  fi

  if [ "${3}" == "${GPIO_ACTIVE_LOW}" ]; then
    echo 1 > "/sys/class/gpio/gpio${1}/active_low"
  fi 
}

echo "${0}: Configure GPIOs ..."

# Discrete inputs: 1, 2, 3, 4
configure_gpio "472" "${GPIO_DIRECTION_INPUT}" "${GPIO_ACTIVE_HIGH}"
configure_gpio "471" "${GPIO_DIRECTION_INPUT}" "${GPIO_ACTIVE_HIGH}"
configure_gpio "470" "${GPIO_DIRECTION_INPUT}" "${GPIO_ACTIVE_HIGH}"
configure_gpio "469" "${GPIO_DIRECTION_INPUT}" "${GPIO_ACTIVE_HIGH}"
# Relays: 1, 2, 3
configure_gpio "456" "${GPIO_DIRECTION_OUTPUT}" "${GPIO_ACTIVE_HIGH}"
configure_gpio "455" "${GPIO_DIRECTION_OUTPUT}" "${GPIO_ACTIVE_HIGH}"
configure_gpio "454" "${GPIO_DIRECTION_OUTPUT}" "${GPIO_ACTIVE_HIGH}"
# Zigbee module: RESET, BOOT
configure_gpio "467" "${GPIO_DIRECTION_OUTPUT}" "${GPIO_ACTIVE_HIGH}"
configure_gpio "462" "${GPIO_DIRECTION_OUTPUT}" "${GPIO_ACTIVE_HIGH}"
# LEDs: RED, GREEN
configure_gpio "452" "${GPIO_DIRECTION_OUTPUT}" "${GPIO_ACTIVE_LOW}"
configure_gpio "453" "${GPIO_DIRECTION_OUTPUT}" "${GPIO_ACTIVE_LOW}"
# Button
configure_gpio "436" "${GPIO_DIRECTION_INPUT}" "${GPIO_ACTIVE_LOW}"

echo "${0}: Turn off LEDs ..."
echo 0 > /sys/class/gpio/gpio452/value
echo 0 > /sys/class/gpio/gpio453/value

echo "${0}: Reset Zigbee module ..."
echo 1 > /sys/class/gpio/gpio462/value
echo 1 > /sys/class/gpio/gpio467/value
sleep 1
echo 0 > /sys/class/gpio/gpio467/value

echo "${0}: Configure 1-Wire ..."

modprobe ds2482

sleep 5

echo ds2482 0x18 > /sys/bus/i2c/devices/i2c-0/new_device

exit 0
