#!/bin/sh

##
# Hooks

# Handle boot hocks
if [ "${RAUC_SLOT_CLASS}" = "boot" ]; then
    if [ "${1}" = "slot-post-install" ]; then
        /usr/lib/rauc/post-install-boot 
    elif [ "${1}" = "slot-pre-install" ]; then
        /usr/lib/rauc/pre-install-boot 
    fi
fi

##
# Fixups

# timesyncd
if [ ! -d /var/lib/systemd/timesync ]; then
    rm /var/lib/systemd/timesync
fi

exit 0
