#!/bin/sh

##
# Hooks

# Handle boot hocks
if [ "${RAUC_SLOT_CLASS}" = "boot" ]; then
    if [ "${1}" = "slot-post-install" ]; then
        /usr/lib/rauc/post-install-boot 
    elif [ "${1}" = "slot-pre-install" ]; then
        /usr/lib/rauc/pre-install-boot 
    fi
fi

##
# Fixups

# timesyncd
if [ -L /var/lib/systemd/timesync ]; then
    rm -f /var/lib/systemd/timesync
fi

# u-boot first stage device tree
if [ -e /usr/sbin/fw_setenv ]; then
    fw_setenv fdt_addr
fi

exit 0
