#!/bin/sh

global linux.bootargs.dyn.root="root=PARTUUID=8d3d53e3-6d49-4c38-8349-aff6859e82fd rootfstype=squashfs ro"

mkdir -p /mnt/system
mount -t squashfs /dev/disk0.hassos-system0 /mnt/system

if [ -f "/mnt/system/boot/bzImage" ]; then
    global bootm.image="/mnt/system/boot/bzImage"
else
    global bootm.image="/mnt/system/boot/zImage"
fi
