#!/bin/sh

global linux.bootargs.dyn.root="root=PARTUUID=a3ec664e-32ce-4665-95ea-7ae90ce9aa20 rootfstype=squashfs ro"

mkdir -p /mnt/system
mount -t squashfs /dev/disk0.hassos-system1 /mnt/system

if [ -f "/mnt/system/boot/bzImage" ]; then
    global bootm.image="/mnt/system/boot/bzImage"
else
    global bootm.image="/mnt/system/boot/zImage"
fi

