#!/bin/sh

global bootm.image="/mnt/disk2/boot/bzImage"

global linux.bootargs.zswap="zswap.enabled=1 zswap.compressor=lz4 zswap.max_pool_percent=20 zswap.zpool=z3fold"
global linux.bootargs.dyn.root="root=/dev/sda3 rootfstype=squashfs ro"
